from __future__ import annotations

from dataclasses import dataclass


LIBYA_ENTITIES = [
    "libya",
    "libyan",
    "tripoli",
    "benghazi",
    "misrata",
    "derna",
    "zawiya",
    "zawia",
    "zuwara",
    "zuwarah",
    "sebha",
    "sabha",
    "sirte",
    "tobruk",
    "ajdabiya",
    "gharyan",
    "tarhuna",
    "nalut",
    "fezzan",
    "cyrenaica",
    "jufra",
    "kufra",
    "murzuq",
    "ras lanuf",
    "brega",
    "ليبيا",
    "ليبي",
    "الليبي",
    "الليبية",
    "طرابلس",
    "بنغازي",
    "مصراتة",
    "درنة",
    "الزاوية",
    "زوارة",
    "سبها",
    "سرت",
    "طبرق",
    "أجدابيا",
    "اجدابيا",
    "غريان",
    "ترهونة",
    "نالوت",
    "فزان",
    "برقة",
    "الجفرة",
    "الكفرة",
    "مرزق",
    "رأس لانوف",
    "البريقة",
]

LIBYA_INSTITUTIONS = [
    "unsmil",
    "srsg",
    "dsrsg",
    "united nations support mission in libya",
    "house of representatives",
    "high council of state",
    "presidential council",
    "government of national unity",
    "gnu",
    "national oil corporation",
    "noc",
    "central bank of libya",
    "cbl",
    "public prosecution",
    "attorney general",
    "audit bureau",
    "administrative control authority",
    "high national elections commission",
    "hnec",
    "ministry of interior",
    "ministry of foreign affairs",
    "ministry of oil",
    "ministry of economy",
    "ministry of health",
    "ministry of education",
    "municipal council",
    "البعثة الأممية",
    "الأمم المتحدة",
    "مجلس النواب",
    "المجلس الأعلى للدولة",
    "المجلس الرئاسي",
    "حكومة الوحدة",
    "حكومة الوحدة الوطنية",
    "المؤسسة الوطنية للنفط",
    "مصرف ليبيا المركزي",
    "النائب العام",
    "النيابة العامة",
    "ديوان المحاسبة",
    "هيئة الرقابة الإدارية",
    "المفوضية الوطنية العليا للانتخابات",
    "وزارة الداخلية",
    "وزارة الخارجية",
    "وزارة النفط",
    "وزارة الاقتصاد",
    "وزارة الصحة",
    "وزارة التعليم",
    "المجلس البلدي",
]

LIBYA_FIGURES = [
    "dbeibah",
    "dabaiba",
    "abdelhamid dbeibah",
    "menfi",
    "mohamed al-menfi",
    "aguila saleh",
    "agila saleh",
    "khaled mishri",
    "takala",
    "haftar",
    "khalifa haftar",
    "saddam haftar",
    "belqasem haftar",
    "osama hammad",
    "bathily",
    "tetteh",
    "koury",
    "williams",
    "الدبيبة",
    "الدبيبه",
    "عبدالحميد الدبيبة",
    "المنفي",
    "محمد المنفي",
    "عقيلة صالح",
    "المشري",
    "تكالة",
    "حفتر",
    "خليفة حفتر",
    "صدام حفتر",
    "بلقاسم حفتر",
    "أسامة حماد",
    "باتيلي",
    "تيتيه",
    "خوري",
    "ستيفاني وليامز",
]

LIBYA_ISSUES = [
    "election",
    "elections",
    "constitutional",
    "constitution",
    "structured dialogue",
    "roadmap",
    "executive authority",
    "governance",
    "municipality",
    "municipal",
    "public services",
    "security",
    "armed group",
    "clashes",
    "crime",
    "arrest",
    "smuggling",
    "drug trafficking",
    "migration",
    "migrant",
    "refugee",
    "deportation",
    "human trafficking",
    "human rights",
    "court",
    "detention",
    "prison",
    "corruption",
    "forgery",
    "economy",
    "banking",
    "exchange rate",
    "liquidity",
    "salary",
    "oil",
    "gas",
    "fuel",
    "electricity",
    "reconstruction",
    "infrastructure",
    "health",
    "education",
    "foreign relations",
    "diplomacy",
    "انتخابات",
    "دستور",
    "دستوري",
    "الحوار المنظم",
    "خارطة طريق",
    "سلطة تنفيذية",
    "حوكمة",
    "بلدية",
    "البلديات",
    "خدمات",
    "أمن",
    "أمني",
    "مسلح",
    "اشتباك",
    "جريمة",
    "قبض",
    "ضبط",
    "تهريب",
    "مخدرات",
    "هجرة",
    "مهاجر",
    "لاجئ",
    "ترحيل",
    "اتجار بالبشر",
    "حقوق الإنسان",
    "محكمة",
    "احتجاز",
    "سجن",
    "فساد",
    "تزوير",
    "اقتصاد",
    "مصرف",
    "سعر الصرف",
    "سيولة",
    "مرتبات",
    "نفط",
    "غاز",
    "وقود",
    "كهرباء",
    "إعمار",
    "بنية تحتية",
    "صحة",
    "تعليم",
    "علاقات خارجية",
    "دبلوماسية",
]

INTERNATIONAL_NOISE = [
    "gaza",
    "israel",
    "hamas",
    "iran",
    "ukraine",
    "russia",
    "trump",
    "syria",
    "lebanon",
    "palestine",
    "sudan",
    "غزة",
    "إسرائيل",
    "حماس",
    "إيران",
    "أوكرانيا",
    "روسيا",
    "ترامب",
    "سوريا",
    "لبنان",
    "فلسطين",
    "السودان",
]

PICS_SECTION_KEYWORDS: dict[str, list[str]] = {
    "United Nations": ["unsmil", "srsg", "dsrsg", "united nations", "security council", "unhcr", "iom", "البعثة الأممية", "الأمم المتحدة", "مجلس الأمن"],
    "Politics": ["structured dialogue", "election", "roadmap", "parliament", "house of representatives", "high council of state", "presidential council", "government", "constitutional", "executive authority", "حوار", "انتخابات", "خارطة", "مجلس النواب", "المجلس الأعلى للدولة", "المجلس الرئاسي", "حكومة", "دستور", "سلطة تنفيذية"],
    "Military & Security": ["security", "armed", "clash", "militia", "army", "crime", "arrest", "smuggling", "drug", "border security", "weapon", "أمن", "أمني", "مسلح", "اشتباك", "جيش", "جريمة", "قبض", "ضبط", "تهريب", "مخدرات", "سلاح"],
    "Human Rights & Rule of Law": ["human rights", "court", "public prosecution", "attorney general", "detention", "prison", "corruption", "forgery", "trafficking", "rule of law", "حقوق الإنسان", "محكمة", "النائب العام", "نيابة", "احتجاز", "سجن", "فساد", "تزوير", "اتجار", "سيادة القانون"],
    "Migration": ["migration", "migrant", "refugee", "deportation", "trafficking", "settlement", "anti-migrant", "هجرة", "مهاجر", "لاجئ", "ترحيل", "اتجار", "توطين"],
    "Economy": ["economy", "budget", "investment", "trade", "free zone", "ports", "exports", "اقتصاد", "ميزانية", "استثمار", "تجارة", "منطقة حرة", "موانئ", "صادرات"],
    "Banking": ["central bank", "banking", "exchange rate", "liquidity", "salary", "digital payment", "مصرف", "سعر الصرف", "سيولة", "مرتبات", "دفع إلكتروني"],
    "Energy": ["oil", "gas", "fuel", "noc", "brega", "electricity", "energy", "نفط", "غاز", "وقود", "المؤسسة الوطنية للنفط", "البريقة", "كهرباء", "طاقة"],
    "Municipalities & Public Services": ["municipality", "municipal", "local council", "public services", "water", "health", "education", "hospital", "بلدية", "البلديات", "مجلس محلي", "خدمات", "مياه", "صحة", "تعليم", "مستشفى"],
    "Reconstruction & Infrastructure": ["reconstruction", "infrastructure", "housing", "roads", "airport", "port", "development projects", "إعمار", "بنية تحتية", "إسكان", "طرق", "مطار", "ميناء", "مشروعات التنمية"],
    "Environment": ["weather", "rain", "flood", "water resources", "pollution", "climate", "agriculture", "طقس", "أمطار", "فيضانات", "موارد مائية", "تلوث", "مناخ", "زراعة"],
    "Regional & International": ["foreign minister", "ambassador", "diplomacy", "bilateral", "italy", "egypt", "tunisia", "turkey", "african union", "وزير الخارجية", "سفير", "دبلوماسي", "ثنائية", "إيطاليا", "مصر", "تونس", "تركيا", "الاتحاد الأفريقي"],
    "Varieties": ["analysis", "opinion", "commentary", "feature", "podcast", "culture", "sport", "heritage", "تحليل", "رأي", "تعليق", "مقال", "بودكاست", "ثقافة", "رياضة", "تراث"],
}

SUBSECTION_KEYWORDS: dict[str, list[str]] = {
    "UNSMIL": ["unsmil", "srsg", "dsrsg", "البعثة الأممية"],
    "Governance": ["government", "cabinet", "minister", "governance", "حكومة", "مجلس الوزراء", "وزير", "حوكمة"],
    "Elections": ["election", "hnec", "electoral", "انتخابات", "المفوضية"],
    "Security": ["security", "armed", "clash", "crime", "arrest", "أمن", "مسلح", "اشتباك", "جريمة", "قبض"],
    "Migration": ["migration", "migrant", "refugee", "هجرة", "مهاجر", "لاجئ"],
    "Increase in anti-migrant sentiment": ["anti-migrant", "settlement", "توطين", "رفض المهاجرين", "مناهضة الهجرة"],
    "Oil & Energy": ["oil", "gas", "fuel", "electricity", "noc", "نفط", "غاز", "وقود", "كهرباء"],
    "Banking": ["central bank", "banking", "exchange rate", "liquidity", "مصرف", "سعر الصرف", "سيولة"],
    "Municipal Services": ["municipality", "public services", "water", "بلدية", "خدمات", "مياه"],
    "Health": ["health", "hospital", "medical", "صحة", "مستشفى", "طبي"],
    "Foreign Relations": ["foreign minister", "ambassador", "diplomacy", "bilateral", "وزير الخارجية", "سفير", "دبلوماسي", "ثنائية"],
}


SECTION_ORDER = [
    "United Nations",
    "Politics",
    "Military & Security",
    "Human Rights & Rule of Law",
    "Migration",
    "Economy",
    "Banking",
    "Energy",
    "Municipalities & Public Services",
    "Reconstruction & Infrastructure",
    "Environment",
    "Regional & International",
    "Varieties",
    "Other",
]


@dataclass(frozen=True)
class RelevanceDecision:
    accepted: bool
    reason: str
    score: int
    positive_matches: list[str]
    noise_matches: list[str]


def all_libya_positive_keywords() -> list[str]:
    return [*LIBYA_ENTITIES, *LIBYA_INSTITUTIONS, *LIBYA_FIGURES, *LIBYA_ISSUES]

